# Generated by Django 4.0.3 on 2022-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_alter_article_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
