# Generated by Django 4.0.3 on 2022-07-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_alter_article_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='simpleapp.creator'),
        ),
    ]
