# Generated by Django 4.0.3 on 2022-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_creator_alter_article_name_alter_article_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
